jobs:
  include:
    - language: node_js
      node_js:
        - "16"
      install:
        - curl -L https://coveralls.io/coveralls-linux.tar.gz | tar -xz -C .
        - npm install
      script:
        - npm run lint
        - npm run test
      after_success: npm run coverage
    - language: python
      python:
        - "3.9"
      install:
        - pip install semgrep
      script:
        - semgrep ci --config auto
branches:
  only:
    - master
